### ISSUE TITLE
ERROR in docker build-push-action action step 

### ISSUE THREAD

**Issue by drighelli** [seandavi/BuildABiocWorkshop2020#15]
Hi @seandavi,

when I reach the docker step it gives me an error on the installation of the `AnnotationDbi` package.

Here the log error section:

> Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
> * installing *source* package ‘AnnotationDbi’ ...
> ** using staged installation
> ** R
> ** inst
> ** tests
> ** byte-compile and prepare package for lazy loading
> Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so':
>   /usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so: undefined symbol: EXTPTR_PTR
> Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
> Execution halted
> ERROR: lazy loading failed for package ‘AnnotationDbi’
> * removing ‘/usr/local/lib/R/site-library/AnnotationDbi’
> Error in i.p(...) : 
>   (converted from warning) installation of package ‘AnnotationDbi’ had non-zero exit status
> Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
> Execution halted
> The command '/bin/sh -c Rscript -e "devtools::install('.', dependencies=TRUE, build_vignettes=TRUE, repos = BiocManager::repositories())"' returned a non-zero code: 1
> Error: exit status 1
> Usage:
> exit status 1

It seems that some Rcpp shared library is missing, any suggestion on how to solve it? 

Thanks,
Dario

**Comment by drighelli** [comment]
During this run, I just moved the docker section up in the actions to not wait too much time for the step check.
Here the complete logs.
[logs_38.zip](https://github.com/seandavi/BuildABiocWorkshop2020/files/4930908/logs_38.zip)

**Comment by LiNk-NY** [comment]
@drighelli Where is your configuration file (`.github/workflows/main.yaml` or similar)?

**Comment by LiNk-NY** [comment]
Follow this conversation here: https://community-bioc.slack.com/archives/CJDMYKG2U/p1594609127244300

**Comment by drighelli** [comment]
> @drighelli Where is your configuration file (`.github/workflows/main.yaml` or similar)?

@LiNk-NY Are you referring to the .github/workflows/basic_checks.yaml ?

I just forked this repo and followed the instructions.
