### ISSUE TITLE
Vignette building killed

### ISSUE THREAD

**Issue by koenvandenberge** [seandavi/BuildABiocWorkshop2020#2]
Hi,

Thanks for making a convenient workshop template.
The creation of our vignette is getting killed without an interpretable error message (https://github.com/kstreet13/bioc2020trajectories/runs/736248107?check_suite_focus=true).
Compilation of the vignette works fine locally.
Any idea what could be causing this?

Thanks!

**Comment by LiNk-NY** [comment]
Hi @koenvandenberge 
I was also getting this error in a separate repository. It's hard to tell. 
I would try to make sure that all the dependencies are accounted perhaps
in a local run of a Docker container.

**Comment by seandavi** [comment]
A killed workflow is likely either exceeding time limits or memory limits. Note that GH actions is limited to 7GB of RAM. I'm not guaranteeing that I am right, but "killed" is not the same as "failed". Given that this is happening in a vignette, I'd look closely at memory requirements.
