### ISSUE TITLE
getting pkgdown to work; problem for pre-existing github.io?

### ISSUE THREAD

**Issue by vjcitn** [seandavi/BuildABiocWorkshop2020#9]
Is there a potential issue with conflict with pre-existing github.io site?

github.com/vjcitn/intmmo is an attempt to produce a workshop site
with  minimal changes to the template.  i already have vjcitn.github.io and
attempt to produce vjcitn.github.io/intmmo by altering DESCRIPTION, basic_checks.yaml,
and _pkgdown.yml, and having a vignette with the name of the repo.
The actions workflow succceeds, the gh-pages branch of intmmo seems properly populated, but vjcitn.github.io/intmmo generates 404 next to some pre-existing content in my gh-pages.

I will try to learn more about pkgdown but I wonder if there is a simple explanation and
workaround.

**Comment by seandavi** [comment]
It looks like your built site is never getting refreshed on gh-pages. Could you check to see if the settings (in settings) for gh-pages is correct (that you are "serving" gh-pages)?

**Comment by vjcitn** [comment]
i think so, as it was cloned from your template?  
![gh](https://user-images.githubusercontent.com/4624066/83971156-c406b480-a8a7-11ea-9dcc-46f8ff98d371.png)

**Comment by vjcitn** [comment]
i think this is sorted; started from scratch with a new repo
